UGR-Lan-Party/ulp-website

README.md, src/components/layout/Header.astro
Hay que adaptar el nav para que se adapte con las páginas necesarias para la LAN Party
=> Cambios en el nav

src/components/layout/Header.astro
Actualizada la estructura jerárquica en el nav
=> :adhesive_bandage: Cambios colaboradores/patrocinadores

src/components/layout/Header.astro
Modificado el orden de los elementos del nav
=> :adhesive_bandage: Cambio orden nav

src/components/layout/Header.astro
Modificado el nombre de un elemento desplegable del nav
=> :adhesive_bandage: Cambio en el nav

src/pages/info/about.astro, src/pages/info/preguntas_frecuentes.astro
Se ha añadido fichero para preguntas frecuentes en la carpeta de info
=> :sparkles: Añadido fichero para FAQs

src/pages/info/preguntas_frecuentes.astro
Añadida la primera versión del contenido de la página de FAQs
=> :sparkles: Contenido de FAQs

src/components/Legalsection.astro, src/pages/info/aviso_legal.astro
Se ha mejorado la estructura del código además de cambiar el formato para que este aparezca en dos columnas.
=> :art: Mejoras y cambios en la estrutura

src/components/plantilla-compe/Competicion.astro, src/components/plantilla-compe/Excelsection.astro, src/components/plantilla-compe/Inscripsection.astro, src/components/plantilla-compe/Localihorasection.astro, src/components/plantilla-compe/Reglasection.astro, src/pages/competiciones/league-of-legends.astro
Diganme que le cambio. Igualmente ya se podrían comenzar a implementar las paginas de competencias y cambios estéticos posteriores no causarían problemas.
La pagina de LOL hay que modificarla con los datos apropiados, ahora esta solo de muestra para que vean como usar el componente.
=> Plantilla juegos

Dockerfile
Reescritura completa del Dockerfile, para mejorar en eficiencia, tamaño y seguridad.
El Dockerfile cuenta ahora con una estructura de _stages_, uno que es el `builder` y otro que es el `runtime`. El stage `builder` es una imagen de node encargada de compilar la página con `npm run build`. El stage `runtime` es una imagen de nginx y toma el sitio generado por el `builder` y lo sirve con la configuración por defecto de nginx.
Quedaría pendiente añadir una configuración personalizada de Nginx para mejorar la seguridad y por ejemplo que la página 404 funcione bien (ahora mismo lo gestion nginx y te pone la por defecto).
Así mismo, antes del `npm install`, se añado `npm install -g npm@10` para asegurarnos de que npm está al último minor y patch de la versión 10. Esto debería de solucionar #4 …
=> Reescritura del Dockerfile

src/components/layout/Header.astro
Se ha mejorado el contenido de la barra de navegación
=> :sparkles: Contenido Navbar

src/components/plantilla-compe/Competicion.astro, src/components/plantilla-compe/Excelsection.astro, src/components/plantilla-compe/Reglasection.astro
Se ha mejorado la plantilla de las competiciones para que se vea correctamente!
=> :sparkles: Mejorada plantilla competiciones

.github/workflows/ci-build.yml
=> implement build ci

src/components/layout/Header.astro, src/components/plantilla-compe/Competicion.astro, src/pages/competiciones/ea-sports-fc-24.astro, src/pages/competiciones/futbolin.astro, src/pages/competiciones/league-of-legends.astro, src/pages/competiciones/mario-kart.astro, src/pages/competiciones/minecraft.astro, src/pages/competiciones/pokemon.astro, src/pages/competiciones/rocket-league.astro, src/pages/competiciones/smash.astro, src/pages/competiciones/valorant.astro, src/pages/competiciones/wii-sports.astro
Se han añadido todas las páginas de todas las competiciones con toda la información referente a ellas
=> :sparkles: Añadidas competiciones

src/components/layout/Header.astro
Se ha modificado el nav en la sección de Participan, añadiendo páginas y subpáginas
=> :sparkles: Modificación nav

src/layouts/Layout.astro
Si el layout no recibe la prop `title`, pone como título _UGR Lan Party_ y si recibe dicha prop, la pone como título añadiéndo al final _| ULP_
=> add fallback title

src/components/Hero.astro
Se ha arreglado el desplazamiento de la etiqueta <p> en dispositivos móviles en la sección del índice
=> :adhesive_bandage: Arreglado estilo Index

src/components/Hero.astro, src/layouts/Layout.astro, src/scripts/countdown.js
Añadida cuenta atras en la pagina inicial :)
=> Cuenta atras :clock11: 

src/components/Hero.astro
Se ha implementado la página de Inscríbete en su primera versión
=> :sparkles: Implementada Página Inscíbete

.github/workflows/publish_docker_image.yml
=> :construction_worker: Add workflow to automate DockerHub Image publication

src/pages/participan/patrocinadores.astro
Se han añadido las RRSS de Taine
=> :sparkles: Añadidas RRSS

nginx.conf
Configuración para servir el sitio directamente como https, en vez de hacer proxy_pass, mientras se sirve por http.
=> Only Https :whale:

src/components/layout/Footer.astro
Se ha arreglado una falta de ortografía en el footer relacionada con Smash Bros
=> Arreglada errata

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/SECURITY.md
Ficheros estandard que suelen haber ante un proyecto público como este.
=> Community Guidelines

src/components/TrailerSection.astro, src/pages/index.astro
=> Trailer YouTube

src/components/plantilla-compe/Inscripsection.astro
Se ha modificado el plazo para inscribirse al miércoles 6 de marzo
=> Modificado plazo.

src/pages/participan/patrocinadores.astro
Se ha ocultado provisionalmente al granada como patrocinador hasta aclarar todo
=> Modificada sección sponsors

src/components/CarouselSection.astro, src/components/Team.astro, src/pages/info/about.astro
He colocado el Carousel en el Sobre nosotros con 4 fotos enlazadas desde el flickr, entonces habría que ver si lo dejamos asi o subimos las imagenes directamente a la web.
Y por ahora el componente no tiene titulo ni nada, ¿le metemos titulo o algo?
=> Nuevo Carousel

src/pages/participan/patrocinadores.astro
Se ha ocultado NoSoloPC de la lista de patrocinadores al seguir sin respuesta de ellos
=> Ocultado de patrocinadores NoSoloPC

src/components/plantilla-compe/Competicion.astro, src/components/plantilla-compe/Premiosection.astro, src/pages/competiciones/ea-sports-fc-24.astro, src/pages/competiciones/futbolin.astro, src/pages/competiciones/league-of-legends.astro, src/pages/competiciones/mario-kart.astro, src/pages/competiciones/minecraft.astro, src/pages/competiciones/pokemon.astro, src/pages/competiciones/rocket-league.astro, src/pages/competiciones/smash.astro, src/pages/competiciones/valorant.astro, src/pages/competiciones/wii-sports.astro
=> Agregada Seccion de Premios y Premios LOL

src/components/Hero.astro, src/scripts/countdown.js
He vuelto a poner la cuenta atras, solo que poniendo la fecha al 9 de marzo del 2025, pese  a que no sea el día de la proxima lan party.
=> Restaurar contador en la pagina principal

.astro/types.d.ts, src/components/layout/Header.astro
He añadido una transición suave cuando el header en sticky aparece para que no sea tan brusco y asi arreglando este bug
https://github.com/UGR-Lan-Party/ulp-website/issues/85
=> Bugfix transicion rara barra de navegacion

src/components/CarouselSection.astro
He corregido el problema de las imagenes mal posicionadas en el carrusel manteniendo el tamaño del mismo. Además, le he cambiado el estilo a los botones respecto al color diferente al hacer hover.
=> Bug fix/carrusel imagenes

.github/workflows/ci-build.yml, Dockerfile, package.json, pnpm-lock.yaml, src/components/CarouselSection.astro
Fixes #119 
Actualizado `pnpm-lock.yaml`
=> Docker build fix

src/pages/blog.astro
Diseño de las cards de las noticias mejoradas, solo he modificado codigo del fichero blog.astro en la carpeta pages.
Resultado:
https://github.com/user-attachments/assets/79f690b3-1e7d-4fe3-94c6-b0b67cedf2a2
Despues tambien se hizo una separacion de la fecha de la creacion de la noticia respecto al titulo quedando la card final así:
=> Feature request/update blog card UI

src/components/CarouselSection.astro, src/pages/index.astro
Añade el carrusel implementedo para el about a la home también:
=> Añadir carrusel a la página de inicio

src/components/layout/Footer.astro
- Se han modificado todos los "svg's" de los iconos, para que fueran todos de la misma fuente.
- Se ha añadido el icono de Discord.
- Se ha ajustado el tamaño para móviles.
=> Feature/139- [BUG] - Arreglar iconos

src/components/layout/Footer.astro, src/layouts/Layout.astro
- Se ha añadido estilos al body y al main para arreglar el bug del footer.
=> Feature/140 Bug Footer

src/components/Contactsection.astro, src/components/Hero.astro
Cambio en la cuenta atrás del home.
=> Feature/153 rediseño de la cuenta atrás del home

src/components/Hero.astro
- Se ha corregido el enlace de inscripción.
=> Fixed button link

src/components/SponsorCard.astro
Cambio en el fondo de las cards de patrocinadores en modo oscuro
=> bug resolved

src/components/contactButton.astro
=> Bug/175 cambiar colores de botón de contacto en sección de patrocinadores (modo oscuro)

.gitignore
Añadidos ficheros al gitignore fix #193
=> Añadidos ficheros al gitignore fix #193

src/components/Contactsection.astro, src/components/Faq.astro, src/components/layout/Footer.astro
Actualizado correos de contacto. #191
=> Actualizado correos de contacto

src/components/Faq.astro, src/scripts/pagination.js
Justificado texto de respuestas de la mitad izquierda.
=> Feature/172 mejorar diseño de componente faq
